export const SIGNUP_USER_ERROR = "SIGNUP_USER_ERROR";
export const SIGNUP_USER_START = "SIGNUP_USER_START";
export const SIGNUP_USER_DEFAULT = "SIGNUP_USER_DEFAULT";
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const SIGNUP_USER = "SIGNUP_USER";
